"""
Exercise 4 — Answers
====================
Fill this in after running exercise4_mcp_client.py.
"""

# ── Basic results ──────────────────────────────────────────────────────────

# Tool names as shown in "Discovered N tools" output.
TOOLS_DISCOVERED = ["search_venues", "get_venue_details"]

QUERY_1_VENUE_NAME    = "The Haymarket Vaults"
QUERY_1_VENUE_ADDRESS = "1 Dalry Road, Edinburgh"
QUERY_2_FINAL_ANSWER  = "It seems there are no currently available Edinburgh venues that can accommodate 300 guests with vegan options. Would you like to try adjusting the capacity requirements or dietary filters?"

# ── The experiment ─────────────────────────────────────────────────────────
# Required: modify venue_server.py, rerun, revert.

EX4_EXPERIMENT_DONE = True   # True or False

# What changed, and which files did or didn't need updating? Min 30 words.
EX4_EXPERIMENT_RESULT = """
When 'The Albanach' was changed to 'full', the agent automatically selected 'The Haymarket Vaults' instead. Notably, I only had to update `mcp_venue_server.py`. I didn't have to touch the agent code or any tools list inside the agent script because the tools and state are dynamically discovered from the server.
"""

# ── MCP vs hardcoded ───────────────────────────────────────────────────────

LINES_OF_TOOL_CODE_EX2 = 0   # count in exercise2_langgraph.py
LINES_OF_TOOL_CODE_EX4 = 0   # count in exercise4_mcp_client.py

# What does MCP buy you beyond "the tools are in a separate file"? Min 30 words.
MCP_VALUE_PROPOSITION = """
MCP allows complete decoupling between the agent runtime and the tool execution environment. It means that we can write a single, standardized server exposing these tools, and any number of disparate client agent frameworks (LangGraph, Rasa, etc.) can immediately discover and use those tools at runtime without us having to duplicate any Python tool execution logic.
"""

# ── Week 5 architecture ────────────────────────────────────────────────────
# Describe your full sovereign agent at Week 5 scale.
# At least 5 bullet points. Each bullet must be a complete sentence
# naming a component and explaining why that component does that job.

WEEK_5_ARCHITECTURE = """
- A LangGraph automated research agent that autonomously crawls the web, aggregates venue information, and searches availability.
- A Rasa Pro CALM digital employee handling live stakeholder interactions, strictly enforcing safety constraints and business rules.
- An MCP Shared Tool Server providing unified, secure access to the venue database and booking functions to both agents simultaneously.
- A secure Database layer holding all persistent constraints, venue capacities, and vegan availabilities.
- A Monitoring layer ensuring the LangGraph agent doesn't hallucinate calls, and tracking all dialogue generated by the CALM agent.
"""

# ── The guiding question ───────────────────────────────────────────────────
# Which agent for the research? Which for the call? Why does swapping feel wrong?
# Must reference specific things you observed in your runs. Min 60 words.

GUIDING_QUESTION_ANSWER = """
The LangGraph agent is perfect for the initial research phase because of its dynamic capability to chain functions and handle complex instructions gracefully, like checking a secondary venue autonomously when 'The Albanach' was full. Conversely, the Rasa CALM agent is mandatory for the telephone confirmation phase because we require deterministic execution of business rules — it guarantees we do not over-approve a deposit. Swapping them feels wrong because a LangGraph agent taking real bookings could be tricked into bypassing financial limits, while a Rasa agent looking up research would be far too tedious to configure for open-state exploration.
"""
